# Generated by Django 3.2 on 2021-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
