# Generated by Django 3.2 on 2021-05-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210503_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='chatuser',
        ),
    ]
